<?xml version="1.0" encoding="utf-8"?><Database Name="Estadistica" Class="EstadisticaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-AN6UI64;Initial Catalog=Estadistica;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EstadisticaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.AsistenciaActividad" Method="AsistenciaActividad">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaActividadResult">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaActividad_Fechas" Method="AsistenciaActividad_Fechas">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaActividad_FechasResult">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaDevocional" Method="AsistenciaDevocional">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaDevocionalResult">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaDevocional_Fechas" Method="AsistenciaDevocional_Fechas">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaDevocional_FechasResult">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaEscuela_Fechas" Method="AsistenciaEscuela_Fechas">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaEscuela_FechasResult">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaVigilia" Method="AsistenciaVigilia">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaVigiliaResult">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaVigilia_Fechas" Method="AsistenciaVigilia_Fechas">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaVigilia_FechasResult">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaActividadEspecial" Method="AsistenciaActividadEspecial">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaActividadEspecialResult">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaActividadEspecial_Fechas" Method="AsistenciaActividadEspecial_Fechas">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaActividadEspecial_FechasResult">
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaPromedio" Method="AsistenciaPromedio">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaPromedioResult">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AsistenciaEscuela" Method="AsistenciaEscuela">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AsistenciaEscuelaResult">
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PorcentajeSinRetirarse" Method="PorcentajeSinRetirarse">
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="Date" />
    <ElementType Name="PorcentajeSinRetirarseResult">
      <Column Name="y" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="name" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>